### ISSUE TITLE
Wrong source and target path created

### ISSUE THREAD

**Issue by tiboth** [google/dwh-migration-tools#70]
During testing the migration-tool we were blocked by a strange error message: Error while Calculating GCS size for workflow projects/30322705XXXX/locations/eu/workflows/90ae6fa8-80b7-459f-9f4e-aa24ccd1xxxx: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Max length for bucket name without dots exceeded. Max length='63', actual='101'.

The built source and target paths are: project-id\Translation_HiveQL2BQ-2022-07-26-5484364d-d729-469d-a736-1d8812744008\

It seems that the Windows path.separator is used by the tool and the GCS considers the whole path as bucket name.

**Comment by xiashang0624** [comment]
Hi, sorry about the delayed reply.  The error message seems indicating that the GCS bucket name is [too long](https://cloud.google.com/storage/docs/naming-buckets#:~:text=Bucket%20names%20must%20contain%203,no%20longer%20than%2063%20characters.).  What `gcs_bucket` did you use in the config.yaml file https://github.com/google/dwh-migration-tools/blob/6f4ffe886d508b1993b0c3773b017f642bb29b20/client/config.yaml#L20

**Comment by xiashang0624** [comment]
We encountered a similar issue and turns out this is because the file path in Windows OS.  This PR added support for Windows 10 and clarified this in the user guide: https://github.com/google/dwh-migration-tools/pull/98.  Closing this now.
